// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"time"
)

type LedgerRecord struct {
	ID                      int64     `json:"id"`
	DataID                  string    `json:"dataId"`
	TransactionHash         string    `json:"transactionHash"`
	BusinessName            string    `json:"businessName"`
	BusinessContractAddress string    `json:"businessContractAddress"`
	ProtocolName            string    `json:"protocolName"`
	ProtocolUri             int64     `json:"protocolUri"`
	CreatedAt               time.Time `json:"createdAt"`
	UpdatedAt               time.Time `json:"updatedAt"`
}
