# Configuration vars for cmd/app
[app]
name = "go-gRPC-web"
port = ":8080"
idle-timeout = 5 # As seconds
print-routes = false
prefork = false
production = false

[app.tls]
enable = false
cert-file = "./storage/selfsigned.crt"
key-file = "./storage/selfsigned.key"

[chain]
url = "http://192.168.1.115:13000"
filekey = '''{"uuid":"123f1bf5-5599-45c4-8566-9a6440ba359f","address":"zltc_Z1pnS94bP4hQSYLs4aP4UwBP9pH8bEvhi","cipher":{"aes":{"cipher":"aes-128-ctr","cipherText":"8f6de52c0be43ae438feddea4c210772da23b9333242b7416446eae889b594e0","iv":"1ad693b4d8089da0492b9c8c49bc60d3"},"kdf":{"kdf":"scrypt","kdfParams":{"DKLen":32,"n":262144,"p":1,"r":8,"salt":"309210a97fbf705eed7bf3485c16d6922a21591297b52c0c59b4f7495863e300"}},"cipherText":"8f6de52c0be43ae438feddea4c210772da23b9333242b7416446eae889b594e0","mac":"335fab3901f8f5c4408b7d6a310ec29cf5bd3792deb696f1b10282e823241c96"},"isGM":true}'''

[logger]
time-format = "" # https://pkg.go.dev/time#pkg-constants, https://github.com/rs/zerolog/blob/master/api.go#L10
level = 0 # panic -> 5, fatal -> 4, error -> 3, warn -> 2, info -> 1, debug -> 0, trace -> -1
prettier = true

[middleware.compress]
enable = true
level = 1

[middleware.recover]
enable = true

[middleware.monitor]
enable = false
path = "/monitor"

[middleware.pprof]
enable = true

[middleware.limiter]
enable = false
max = 20
expiration_seconds = 60

[middleware.jwt]
secret = "secret"
expiration_seconds = 3600

[middleware.filesystem]
enable = false
browse = true
max_age = 3600
index = "index.html"
root = "./storage/public"
