# Configuration vars for cmd/app
[app]
name = "go-gRPC-web"
port = ":8080"
idle-timeout = 5 # As seconds
print-routes = false
prefork = false
production = false

[app.tls]
enable = false
cert-file = "./storage/selfsigned.crt"
key-file = "./storage/selfsigned.key"

[chain]
url = "http://192.168.1.115:13000"

[logger]
level = 0 # panic -> 5, fatal -> 4, error -> 3, warn -> 2, info -> 1, debug -> 0, trace -> -1
prettier = true

[middleware.compress]
enable = true
level = 1

[middleware.recover]
enable = true

[middleware.monitor]
enable = false
path = "/monitor"

[middleware.pprof]
enable = true

[middleware.limiter]
enable = false
max = 20
expiration_seconds = 60

[middleware.jwt]
enable = false
secret = "secret"
expiration_seconds = 3600

[middleware.filesystem]
enable = false
browse = true
max_age = 3600
index = "index.html"
root = "./storage/public"
